name: Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: go get lint command
        run: go get -u golang.org/x/lint/golint & go install $GOPATH/src/golang.org/x/lint/golint

      - name: Go lint
        run: golint -set_exit_status ./...

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test -v ./...

      - name: Build
        run: go build -v ./cli/s3go
